// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY9h0aLALtJXVuKSLeOTpDC3jViIKvmPQ',
    appId: '1:972945617806:web:698f4ff85911c3b3a7aadf',
    messagingSenderId: '972945617806',
    projectId: 'edulingo-auth',
    authDomain: 'edulingo-auth.firebaseapp.com',
    storageBucket: 'edulingo-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_UbA3vIdeTXVjh4-eGqVa-fwaoW89CGs',
    appId: '1:972945617806:android:88969ca49f1d3b09a7aadf',
    messagingSenderId: '972945617806',
    projectId: 'edulingo-auth',
    storageBucket: 'edulingo-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzgC6bXZKomsGM9NJ9p16cBsBBm1MyYxU',
    appId: '1:972945617806:ios:53863791e0610ccba7aadf',
    messagingSenderId: '972945617806',
    projectId: 'edulingo-auth',
    storageBucket: 'edulingo-auth.firebasestorage.app',
    iosBundleId: 'com.example.eduLingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzgC6bXZKomsGM9NJ9p16cBsBBm1MyYxU',
    appId: '1:972945617806:ios:53863791e0610ccba7aadf',
    messagingSenderId: '972945617806',
    projectId: 'edulingo-auth',
    storageBucket: 'edulingo-auth.firebasestorage.app',
    iosBundleId: 'com.example.eduLingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY9h0aLALtJXVuKSLeOTpDC3jViIKvmPQ',
    appId: '1:972945617806:web:df839d39f2df26c2a7aadf',
    messagingSenderId: '972945617806',
    projectId: 'edulingo-auth',
    authDomain: 'edulingo-auth.firebaseapp.com',
    storageBucket: 'edulingo-auth.firebasestorage.app',
  );
}
